"""empty message

Revision ID: 1f13984c3ed8
Revises: dd2d28b35b78
Create Date: 2023-12-17 19:14:25.370704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f13984c3ed8'
down_revision = 'dd2d28b35b78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint('favorites_favorite_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['favorite_people_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_favorite_people_id_fkey', 'planets', ['favorite_people_id'], ['id'])

    # ### end Alembic commands ###
