"""empty message

Revision ID: 67541c8322bb
Revises: fe3ebd4fadf0
Create Date: 2023-12-15 01:44:54.454847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67541c8322bb'
down_revision = 'fe3ebd4fadf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_planet_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['favorite_planet_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('favorite_planet_id')

    # ### end Alembic commands ###
