"""empty message

Revision ID: dd2d28b35b78
Revises: 67541c8322bb
Create Date: 2023-12-17 18:53:30.733257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2d28b35b78'
down_revision = '67541c8322bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorite_people_id', sa.Integer(), nullable=True))
        batch_op.alter_column('favorite_planet_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key(None, 'planets', ['favorite_people_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('favorite_planet_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('favorite_people_id')

    # ### end Alembic commands ###
